# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

from Controllers import operation_service
from entities.articolo import Articolo
from entities.operazione import Operazione, letturaDatabaseArticoli
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from Controllers.operation_service import calcolaVenditeTotali, ordinamentoOperazioni, giacenzaMediaMensile, \
    indiceRotazione
from entities.operazione import letturaDatabaseOperazioni


class adminWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 893)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_9)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.spinBox = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox)
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_7)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)

        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.aggiuntaVendita)

        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem)
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_8)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.aggiuntaGiacenza)
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem1)
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_8)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.aggiuntaArticolo)
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_3)
        self.gridLayout.addWidget(self.frame, 1, 2, 3, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_2.setStyleSheet("QFrame#frame {\n"
                                   "    background-color: #ffffff;\\n\n"
                                   "    border-radius: 12px;\\n\n"
                                   "    border: 1px solid #e0e6ed;\\n\n"
                                   "    padding: 16px;\\n\n"
                                   "    box-shadow: 0 4px 12px rgba(0,0,0,0.05);\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_15)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_9)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_14)
        self.spinBox_3 = QtWidgets.QSpinBox(parent=self.frame_2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_3)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_16)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_10)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_18)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_11)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_19)
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_12)
        self.label_20 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_20)
        self.spinBox_4 = QtWidgets.QSpinBox(parent=self.frame_2)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_4)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_22)
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_14)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_23)
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_15)
        self.label_24 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_24)
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_16)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.modificaVendita)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.modificaGiacenza)
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout.setItem(18, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem4)
        self.label_28 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_29)
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_18)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.eliminaArticolo)
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_7)
        self.gridLayout.addWidget(self.frame_2, 1, 3, 3, 1)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 4)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setMinimumSize(16777215, 100)
        self.frame_3.setMaximumSize(16777215, 100)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_25 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_3)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(" ")
        self.comboBox.addItem("uomo")
        self.comboBox.addItem("donna")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_26 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout.addWidget(self.label_26)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.frame_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem(" ")
        self.comboBox_2.addItem("calzatura")
        self.comboBox_2.addItem("borsa")
        self.comboBox_2.addItem("abbigliamento")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.label_27 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout.addWidget(self.label_27)
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout.addWidget(self.lineEdit_17)
        self.label_30 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout.addWidget(self.label_30)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.frame_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_3.setObjectName("comboBox_3")

        self.comboBox_3.addItem(" ")
        self.comboBox_3.addItem("Italia")
        self.comboBox_3.addItem("Germania")
        self.comboBox_3.addItem("Francia")
        self.comboBox_3.addItem("Spagna")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.applicaFiltri)
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 1)
        self.graphicsView = BarChartCanvas(self.widget)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 700))
        self.graphicsView.setStyleSheet("none")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 1, 0, 3, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 22))
        self.menubar.setObjectName("menubar")
        self.menuControlloMagazzino = QtWidgets.QMenu(parent=self.menubar)
        self.menuControlloMagazzino.setObjectName("menuControlloMagazzino")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuControlloMagazzino.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Aggiungi Vendita"))
        self.label_5.setText(_translate("MainWindow", "SKU"))
        self.label_6.setText(_translate("MainWindow", "Quantità"))
        self.label_7.setText(_translate("MainWindow", "Paese"))
        self.pushButton.setText(_translate("MainWindow", "Conferma Operazione"))
        self.label_8.setText(_translate("MainWindow", "Aggiungi Giacenza"))
        self.label_3.setText(_translate("MainWindow", "SKU"))
        self.label_4.setText(_translate("MainWindow", "Quantità"))
        self.pushButton_2.setText(_translate("MainWindow", "Conferma Operazione"))
        self.label_10.setText(_translate("MainWindow", "Aggiungi Articolo"))
        self.label_11.setText(_translate("MainWindow", "SKU"))
        self.label_12.setText(_translate("MainWindow", "Genere"))
        self.label_13.setText(_translate("MainWindow", "Tipologia"))
        self.pushButton_3.setText(_translate("MainWindow", "Conferma Operazione"))
        self.label.setText(_translate("MainWindow", "Modifica Vendita"))
        self.label_15.setText(_translate("MainWindow", "ID Operazione"))
        self.label_2.setText(_translate("MainWindow", "SKU"))
        self.label_14.setText(_translate("MainWindow", "Quantità"))
        self.label_16.setText(_translate("MainWindow", "Paese"))
        self.label_17.setText(_translate("MainWindow", "Modifica Giacenza"))
        self.label_18.setText(_translate("MainWindow", "ID Operazione"))
        self.label_19.setText(_translate("MainWindow", "SKU"))
        self.label_20.setText(_translate("MainWindow", "Quantità"))
        self.label_21.setText(_translate("MainWindow", "Modifica Articolo"))
        self.label_22.setText(_translate("MainWindow", "SKU"))
        self.label_23.setText(_translate("MainWindow", "Genere"))
        self.label_24.setText(_translate("MainWindow", "Tipologia"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.label_25.setText(_translate("MainWindow", "Genere"))
        self.label_26.setText(_translate("MainWindow", "Tipologia"))
        self.label_27.setText(_translate("MainWindow", "SKU"))
        self.label_28.setText(_translate("MainWindow", "Elimina Articolo"))
        self.label_29.setText(_translate("MainWindow", "SKU"))
        self.label_30.setText(_translate("MainWindow", "Paese"))
        self.pushButton_7.setText(_translate("MainWindow", "Conferma Operazione"))
        self.pushButton_8.setText(_translate("MainWindow", "Applica Filtri"))
        self.menuControlloMagazzino.setTitle(_translate("MainWindow", "ControlloMagazzino"))

    def aggiuntaVendita(self):
        # O=Operazione()
        # x = O.aggiungiVendita(self.lineEdit_5.text(),self.spinBox.value(), self.lineEdit_7.text())
        # print("Vendita aggiunta")

        SKU_AV = self.lineEdit_5.text()
        N_AV = self.spinBox.value()
        P_AV = self.lineEdit_7.text()
        if SKU_AV == '' or N_AV == '' or P_AV == '':
            a = QMessageBox()
            a.setWindowTitle('ERRORE')
            a.setText('Ci sono dei campi vuoti')
            a.exec()
        else:
            lista_articoli = letturaDatabaseArticoli("Model/databaseArticoli.txt")
            n = 0
            for art in lista_articoli:
                if art['sku'] == SKU_AV:
                    n += 1
            if n == 1:
                O = Operazione()
                x = O.aggiungiVendita(SKU_AV, N_AV, P_AV)
            else:
                o = QMessageBox()
                o.setWindowTitle('ERRORE')
                o.setText('SKU NON ESISTENTE')
                o.exec()

    def aggiuntaGiacenza(self):
        # O=Operazione()
        # x = O.aggiungiGiacenza(self.lineEdit_3.text(), self.spinBox_2.value())
        # print("Giacenza aggiunta")

        SKU_AG = self.lineEdit_3.text()
        N_AG = self.spinBox_2.value()

        if SKU_AG == '' or N_AG == '':
            a = QMessageBox()
            a.setWindowTitle('ERRORE')
            a.setText('Ci sono dei campi vuoti')
            a.exec()
        else:
            lista_articoli = letturaDatabaseArticoli("Model/databaseArticoli.txt")
            n = 0
            for art in lista_articoli:
                if art['sku'] == SKU_AG:
                    n += 1
            if n == 1:
                O = Operazione()
                O.aggiungiGiacenza(SKU_AG, N_AG)
            else:
                o = QMessageBox()
                o.setWindowTitle('ERRORE')
                o.setText('SKU NON ESISTENTE')
                o.exec()

    def aggiuntaArticolo(self):
        SKU_ART = self.lineEdit_4.text()
        GENERE_ART = self.lineEdit_6.text()
        TIPO_ART=self.lineEdit_8.text()

        if SKU_ART == '' or TIPO_ART == '' or GENERE_ART == '':
            QMessageBox.critical(None,'Errore','Ci sono dei campi vuoti')
            return
        if str(GENERE_ART) != "uomo" and str(GENERE_ART) != 'donna':
            QMessageBox.critical(None,'Errore','Genere non valido, deve essere uomo o donna')
            return
        else:
            lista_articoli = letturaDatabaseArticoli("Model/databaseArticoli.txt")
            n = 0
            for art in lista_articoli:
                if art['sku']==SKU_ART:
                    n += 1
            if n == 0:
                A = Articolo(self.lineEdit_4.text(), self.lineEdit_6.text(), self.lineEdit_8.text())
                x = A.aggiungiArticolo()
            else:
                QMessageBox.critical(None,'Errore','SKU ESISTENTE')

    def modificaVendita(self):

        SKU_MV = str(self.lineEdit.text())
        lista_articoli = letturaDatabaseArticoli("Model/databaseArticoli.txt")
        n = False
        for art in lista_articoli:
            if art['sku'] == SKU_MV or SKU_MV == '':
                n = True
        if n is True:
            OpP = Operazione()
            t = OpP.modificaVendita(int(self.lineEdit_9.text()), str(self.lineEdit.text()), str(self.spinBox_3.value()),
                                    str(self.lineEdit_10.text()))
            if t == True:
                y = QMessageBox()
                y.setWindowTitle('ERRORE')
                y.setText("L'operazione cercata non è una vendita")
                y.exec()
            if t == 'non trovato':
                l = QMessageBox()
                l.setWindowTitle('ERRORE')
                l.setText("L'operazione non esiste")
                l.exec()
        else:
            p = QMessageBox()
            p.setWindowTitle('ERRORE')
            p.setText("SKU non esiste")
            p.exec()

    def modificaGiacenza(self):
        SKU_MG = self.lineEdit_12.text()

        lista_articoli = letturaDatabaseArticoli("Model/databaseArticoli.txt")
        n = False
        for art in lista_articoli:
            if art['sku'] == SKU_MG or SKU_MG == '':
                n = True
        if n is True:
            Opp = Operazione()
            k = Opp.modificaGiacenza(int(self.lineEdit_11.text()), str(self.lineEdit_12.text()), str(self.spinBox_4.value()),
                                     None)
            if k == True:
                p = QMessageBox()
                p.setWindowTitle('ERRORE')
                p.setText("L'operazione selezionata non è una giacenza")
                p.exec()
            elif k == 'Errore':
                u = QMessageBox()
                u.setWindowTitle('ERRORE')
                u.setText("L'operazione non esiste")
                u.exec()
        else:
            w = QMessageBox()
            w.setWindowTitle('ERRORE')
            w.setText("SKU non esiste ")
            w.exec()

    def eliminaArticolo(self):
        A=Articolo()
        x=A.eliminaArticolo(self.lineEdit_18.text())
        print("Articolo Eliminato")

    def applicaFiltri(self):

        lista_operazioni=letturaDatabaseOperazioni("Model/databaseOperazioni.txt")
        lista_articoli=letturaDatabaseArticoli("Model/databaseArticoli.txt")
        operazioniFiltrate = operation_service.filtraOperazioni(lista_operazioni, lista_articoli,
                                                                [str(self.lineEdit_17.text())],
                                                                [str(self.comboBox.currentText())],
                                                                [str(self.comboBox_2.currentText())],
                                                                [str(self.comboBox_3.currentText())])
        print(operazioniFiltrate)


class BarChartCanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.fig = Figure(figsize=(10, 4), tight_layout=True)
        self.axes = self.fig.add_subplot(111)
        super().__init__(self.fig)

        if parent:
            self.setParent(parent)  # Imposta il parent separatamente

        self.setStyleSheet("""
            background-color: transparent;
            border-radius: 12px;
            border: 1px solid #e0e6ed;
        """)
        self.plot_data()

    def plot_data(self):
        mesi = ["Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic"]
        lista_operazioni = letturaDatabaseOperazioni("Model/databaseOperazioni.txt")
        vendite = calcolaVenditeTotali(lista_operazioni)
        giacenze = [0] * 12

        for i in range(12):
            operazioni_ordinate = ordinamentoOperazioni(lista_operazioni, i + 1)
            giacenze[i] = giacenzaMediaMensile(operazioni_ordinate, i + 1)

        max_vendite = max(vendite) if vendite else 1
        rotazione = indiceRotazione(vendite, giacenze)
        rotazione_multiplo = [val * (max_vendite / 10) for val in rotazione]

        x = np.arange(len(mesi))
        width = 0.35

        self.axes.clear()
        self.axes.bar(x - width / 2, vendite, width, label='Vendite Totali', color='#455C75')
        self.axes.bar(x + width / 2, giacenze, width, label='Giacenza Media', color='#E0BC47')
        self.axes.plot(x, rotazione_multiplo, color='black', marker='o', label='Indice Rotazione', linewidth=2)

        for i, val in enumerate(rotazione):
            self.axes.annotate(
                f'{val:.2f}',
                (x[i], rotazione_multiplo[i]),
                textcoords="offset points",
                xytext=(0, 10),
                ha='center',
                fontsize=8,
                color='black'
            )

        self.axes.set_xticks(x)
        self.axes.set_xticklabels(mesi, fontsize=10)
        self.axes.set_ylabel('Quantità', fontsize=11)
        self.axes.set_title('Andamento Mensile Vendite e Giacenza', fontsize=12, weight='bold')
        self.axes.legend()
        self.axes.grid(axis='y', linestyle='--', alpha=0.3)
        self.draw()