# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from Controllers.operation_service import calcolaVenditeTotali, giacenzaMediaMensile, ordinamentoOperazioni, \
        indiceRotazione
import numpy as np

from entities.operazione import letturaDatabaseOperazioni


class adminWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 893)
        MainWindow.setStyleSheet("/* Stile principale - Sfondo e tipografia */\n"
"QMainWindow {\n"
"    background-color: #f5f7fa;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"/* Pannello laterale stile \"card\" */\n"
"QFrame#frame {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #e0e6ed;\n"
"    padding: 16px;\n"
"    box-shadow: 0 4px 12px rgba(0,0,0,0.05);\n"
"}\n"
"\n"
"/* Titoli delle sezioni */\n"
"QLabel[text^=\"Aggiungi\"] {\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    color: #4a6cf7;\n"
"    padding: 8px 0;\n"
"    border-bottom: 2px solid #e4e9f2;\n"
"    margin-bottom: 12px;\n"
"}\n"
"\n"
"/* Etichette normali */\n"
"QLabel {\n"
"    font-size: 13px;\n"
"    color: #64748b;\n"
"    padding: 4px 0;\n"
"}\n"
"\n"
"/* Campi di input */\n"
"QLineEdit, QSpinBox {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #4a6cf730;\n"
"}\n"
"\n"
"QLineEdit:focus, QSpinBox:focus {\n"
"    border: 1px solid #4a6cf7;\n"
"    box-shadow: 0 0 0 3px rgba(74, 108, 247, 0.15);\n"
"}\n"
"\n"
"/* Pulsanti principali */\n"
"QPushButton {\n"
"    background-color: #4a6cf7;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px 16px;\n"
"    font-weight: 500;\n"
"    font-size: 14px;\n"
"    margin-top: 12px;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3a5af5;\n"
"    transform: translateY(-1px);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2b4df3;\n"
"    transform: translateY(1px);\n"
"}\n"
"\n"
"/* Pulsante Vendita */\n"
"#pushButton {\n"
"    background-color: #4a6cf7;\n"
"}\n"
"\n"
"/* Pulsante Giacenza */\n"
"#pushButton_2 {\n"
"    background-color: #0e9f6e;\n"
"}\n"
"\n"
"/* Pulsante Articolo */\n"
"#pushButton_3 {\n"
"    background-color: #9061f9;\n"
"}\n"
"\n"
"/* Linea separatrice */\n"
"QFrame[orientation=\"1\"] { /* Horizontal line */\n"
"    background-color: #e4e9f2;\n"
"    height: 2px;\n"
"    margin: 8px 0;\n"
"}\n"
"\n"
"/* Area grafica */\n"
"QGraphicsView {\n"
"    background-color: white;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #e0e6ed;\n"
"}\n"
"\n"
"/* Menu Bar */\n"
"QMenuBar {\n"
"    background-color: white;\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #f1f5f9;\n"
"}\n"
"\n"
"/* Spaziatori trasparenti */\n"
"QSpacerItem {\n"
"    background-color: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_9)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.spinBox = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox)
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem)
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_8)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem1)
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_8)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton_3)
        self.gridLayout.addWidget(self.frame, 1, 2, 3, 1)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 3)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 600))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        # self.graphicsView = QtWidgets.QGraphicsView(parent=self.widget)
        # self.graphicsView.setObjectName("graphicsView")
        self.graphicsView = BarChartCanvas(parent=self.widget)
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 0, 2, 2)
        self.top_left_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.top_left_widget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.top_left_widget.setObjectName("top_left_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.top_left_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.top_left_widget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 45))
        self.menubar.setObjectName("menubar")
        self.menuControlloMagazzino = QtWidgets.QMenu(parent=self.menubar)
        self.menuControlloMagazzino.setObjectName("menuControlloMagazzino")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuControlloMagazzino.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Aggiungi Vendita"))
        self.label_5.setText(_translate("MainWindow", "SKU"))
        self.label_6.setText(_translate("MainWindow", "Quantità"))
        self.label_7.setText(_translate("MainWindow", "Paese"))
        self.label_8.setText(_translate("MainWindow", "Aggiungi Giacenza"))
        self.label_3.setText(_translate("MainWindow", "SKU"))
        self.label_4.setText(_translate("MainWindow", "Quantità"))
        self.pushButton_2.setText(_translate("MainWindow", "Conferma Operazione"))
        self.label_10.setText(_translate("MainWindow", "Aggiungi Articolo"))
        self.label_11.setText(_translate("MainWindow", "SKU"))
        self.label_12.setText(_translate("MainWindow", "Genere"))
        self.label_13.setText(_translate("MainWindow", "Tipologia"))
        self.pushButton.setText(_translate("MainWindow", "Conferma Operazione"))
        self.pushButton_3.setText(_translate("MainWindow", "Conferma Operazione"))
        self.menuControlloMagazzino.setTitle(_translate("MainWindow", "ControlloMagazzino"))

class BarChartCanvas(FigureCanvas):
    def __init__(self, parent=None):
        fig = Figure(figsize=(10, 4), tight_layout=True)
        self.axes = fig.add_subplot(111)
        super().__init__(fig)
        self.setParent(parent)
        self.setStyleSheet("""
            background-color: white;
            border-radius: 12px;
            border: 1px solid #e0e6ed;
        """)
        self.plot_data()

    def plot_data(self):
        mesi = ["Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic"]
        lista_operazioni=letturaDatabaseOperazioni("Model/databaseOperazioni.txt")
        vendite = calcolaVenditeTotali(lista_operazioni)  # Restituisce lista di 12 int/float
        giacenze = [0] * 12

        for i in range(12):
                operazioni_ordinate=ordinamentoOperazioni(lista_operazioni, i+1)
                giacenze[i]=giacenzaMediaMensile(operazioni_ordinate, i+1)
        
        rotazione=indiceRotazione(vendite, giacenze)

        print ("prova:",giacenze)

        x = np.arange(len(mesi))
        width = 0.35

        self.axes.clear()
        self.axes.bar(x - width/2, vendite, width, label='Vendite Totali', color='#4a6cf7')
        self.axes.bar(x + width/2, giacenze, width, label='Giacenza Media', color='#0e9f6e')

        # Linea: indice rotazione
        self.axes.plot(x, rotazione, color='black', marker='o', label='Indice Rotazione', linewidth=2)


        self.axes.set_xticks(x)
        self.axes.set_xticklabels(mesi, fontsize=10)
        self.axes.set_ylabel('Quantità', fontsize=11)
        self.axes.set_title('Andamento Mensile Vendite e Giacenza', fontsize=12, weight='bold')
        self.axes.legend()
        self.axes.grid(axis='y', linestyle='--', alpha=0.3)
        self.draw()