# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from unittest import skipUnless

from PyQt6.QtCore import Qt
import sys
from PyQt6.QtWidgets import (
    QApplication, QWidget, QPushButton,QHBoxLayout,QVBoxLayout, QTableWidget,
    QGridLayout, QLineEdit, QLabel, QComboBox, QMessageBox)
from PyQt6 import QtCore, QtGui, QtWidgets
from unicodedata import numeric

from Controllers.auth_service import AuthService
from Controllers.operation_service import giacenza_media
from entities.utente import (letturaDatabaseUtenti, get_utente_by_id)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
class Finestra1(QWidget):
    def __init__(self):
        super().__init__()
        self.show()
        self.setWindowTitle("Finestra Iniziale")
        self.setGeometry(200, 200, 300, 200)
        self.F1L = QVBoxLayout()
        self.setLayout(self.F1L)
        self.Accedi = QPushButton("Accedi")
        self.Registrati = QPushButton("Registrati")
        self.Accedi.clicked.connect(self.afa)
        self.Registrati.clicked.connect(self.afr)
        self.F1L.addWidget(self.Accedi)
        self.F1L.addWidget(self.Registrati)
        self.finestraA = FinestraA()
        self.finestraR = FinestraR()
    def afa (self) :
        self.hide()
        self.finestraA = FinestraA()
        self.finestraA.show()
    def afr (self) :
        self.hide()
        self.finestraR = FinestraR()
        self.finestraR.show()



class FinestraA(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Finestra di Accesso")
        self.setGeometry(200, 200, 300, 200)
        self.finestra_m = None
        self.finestra_c = None
        self.finestra_rc = None
        LayoutA = QVBoxLayout()
        LayoutA.addWidget(QLabel("Inserisci Codice Utente \n poi premi accedi"))
        self.L = QLineEdit()
        self.L.setPlaceholderText("Accedi")
        LayoutA.addWidget(self.L)
        b = QPushButton("Accedi")
        LayoutA.addWidget(b)
        self.setLayout(LayoutA)
        b.clicked.connect(self.accesso)
    def accesso(self):
        A = AuthService()
        x = A.loginUtente(self.L.text())
        if x == None:
                pp = QMessageBox()
                pp.setWindowTitle('errore')
                pp.setText("Nome utente non esistente, riprovare")
                pp.exec()
        elif x['ruoloUtente'] == 'Magazziniere':
            self.hide()
            self.finestra_m = FinestraM()
            self.finestra_m.show()
        elif x['ruoloUtente']== 'Commesso':
            self.hide()
            self.finestra_c = FinestraC()
            self.finestra_c.show()
        elif x['ruoloUtente']== 'Responsabile Commerciale':
            self.hide()
            self.finestra_rc = FinestraRC()
            self.finestra_rc.show()
        elif x['ruoloUtente']== 'Responsabile Commerciale':
            self.hide()
            self.finestra_ad = FinestraAD()
            self.finestra_ad.show()


class FinestraR(QWidget):
    def __init__(self):
        super().__init__()
        self.finestra_1 = None
        self.setWindowTitle("Finestra di Registrazione")
        self.setGeometry(200, 200, 300, 200)
        self.LA = QGridLayout()
        self.setLayout(self.LA)
        #self.Main_window = QWidget()
        self.VL1 = QVBoxLayout()
        self.VL2 = QVBoxLayout()
        # VL3 = QVBoxLayout()
        self.VL4 = QVBoxLayout()
        self.VL3 = QVBoxLayout()
        self.LA.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # VL1.setAlignment(Qt.AlignTop)

        #self.PW = QLineEdit()
        #self.PW.setEchoMode(QLineEdit.Password)
        #Main_window.setLayout(LA)
        self.LA.addLayout(self.VL1, 1, 0)
        self.LA.addLayout(self.VL2, 1, 1)
        self.LA.addLayout(self.VL3, 1, 2)
        self.LA.addLayout(self.VL4, 0, 0)
        # LA.addLayout(VL5,2,0)
        #p = QLabel('INSERIRE NOME COGNOME E RUOLO')

        self.LA.addWidget(QLabel('INSERIRE NOME COGNOME E RUOLO'), 0, 0)
        self.Label1 = QLineEdit()
        self.Label2 = QLineEdit()
        self.label3 = QComboBox()
        #self.ruolo = ["Magazziniere", "Commesso", "Responsabile  Commerciale"]
        #for r in self.ruolo :
            #self.label3.addItems(r)
        self.label3.addItem("Magazziniere")
        self.label3.addItem("Commesso")
        self.label3.addItem("Responsabile Commerciale")
        self.Label1.setPlaceholderText("Mario")
        self.Label2.setPlaceholderText("Rossi")
        self.VL1.addWidget(QLabel('NOME'))
        self.VL1.addWidget(self.Label1)
        self.VL2.addWidget(QLabel('COGNOME'))

        # VL1.setContentsMargins(10,10,10,10)
        # VL1.setSpacing(200)
        self.VL2.addWidget(self.Label2)
        # VL3.addWidget(QLabel('Nome Utente'))
        # VL3.addWidget(PW)
        self.VL3.addWidget(QLabel('RUOLO'))
        self.VL3.addWidget(self.label3)
        self.ButtonA = QPushButton('Registrati')
        self.LA.addWidget(self.ButtonA, 3, 2)
        self.ButtonA.clicked.connect(self.bottoneCliccato)

    def bottoneCliccato (self) :
        #nome = self.Label1.text()
        #cognome = self.Label2.text()
        #ruolo = self.label3.currentText()
        b = AuthService()
        f = b.aggiungiUtenti(self.Label1.text(), self.Label2.text(), self.label3.currentText())
        a = QMessageBox()
        a.setWindowTitle('Nome Utente')
        a.setText('Registrazione avvenuta con successo \nIl tuo nome Utente è:'+ f )
        a.exec()

        self.hide()
        self.finestra_1 = Finestra1()
        self.finestra_1.show()


#“S.split([sep[, max]])” ritorna una lista contenente le parti di “S” divise usando i caratteri di “sep” come separatore. “Max” è il numero massimo di divisioni eseguite.
#Il valore di default di “sep” è ogni spazio bianco



class FinestraM(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Finestra dei Magazzinieri")
        self.setGeometry(200, 200, 300, 200)
        layoutM = QVBoxLayout()
        layoutH1 = QHBoxLayout()
        layoutH2 = QHBoxLayout()
        layoutH3 = QHBoxLayout()
        layoutH4 = QHBoxLayout()
        layoutH5 = QHBoxLayout()
        layoutH6 = QHBoxLayout()
        self.numero_ag = QLineEdit()
        self.numero_ag.setMaximumWidth(100)
        self.sku_ag = QLineEdit()
        self.sku_ag.setMaximumWidth(100)
        self.numero_mg = QLineEdit()
        self.numero_mg.setMaximumWidth(100)
        self.sku_mg = QLineEdit()
        self.sku_mg.setMaximumWidth(100)
        self.id_Giacenza = QLineEdit()
        self.id_Giacenza.setMaximumWidth(100)
        aggiungi = QPushButton("Aggiungi")
        modifica = QPushButton("Modifica")

        layoutH5.addWidget(QLabel('NUOVA GIACENZA'))
        #layoutH5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layoutM.addLayout(layoutH5)


        layoutH1.addWidget(QLabel('SKU:'))
        layoutH1.addWidget(self.sku_ag)
        layoutH1.addWidget(QLabel('QUANTITÀ:'))
        layoutH1.addWidget(self.numero_ag)
        layoutM.addLayout(layoutH1)

        layoutM.addWidget(aggiungi)

        layoutH6.addWidget(QLabel('MODIFICA GIACENZA'))
        #layoutH6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layoutM.addLayout(layoutH6)

        layoutH3.addWidget(QLabel('ID GIACENZA:'))
        layoutH3.addWidget(self.numero_mg)
        layoutH3.addWidget(QLabel('SKU:'))
        layoutH3.addWidget(self.sku_mg)
        layoutH3.addWidget(QLabel('QUANTITÀ:'))
        layoutH3.addWidget(self.id_Giacenza)
        layoutM.addLayout(layoutH3)

        layoutM.addWidget(modifica)
        #layoutM.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.setLayout(layoutM)


class FinestraC(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Finestra dei Commessi")
        self.setGeometry(200, 200, 300, 200)

class FinestraRC(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Finestra dei Responsabili Commerciali")
        self.setGeometry(200, 200, 300, 200)

class FinestraAD(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Finestra Signore Supremo")
        self.setGeometry(200, 200, 300, 200)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    finestra = Finestra1()
    finestra.show()
    sys.exit(app.exec())